spring.application.name=api

# Database Configuration (H2 - Banco para Testes)
#spring.datasource.url=jdbc:h2:mem:foodonhands
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Database Configuration (PostgreeSQL - Banco para Produção)
spring.datasource.url=jdbc:postgresql://localhost:5432/food_on_hands_db
spring.datasource.username=postgres
spring.datasource.password=7007
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret
api.security.token.secret=${JWT_SECRET:my-super-secret-key-food-on-hands-2026}
